name: learn-gh-actions
on:
  workflow_dispatch:
jobs:
  build-and-test-solution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          dotnet-version: 3.1.x
          
      - name: build solution    
        run: dotnet build
        
      - name: run tests    
        run: dotnet test
        
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
      
